name: CI - Backend Java

on:
  push:
    branches: [ "main", "develop" ] # Cuando alguien sube código a estas ramas
  pull_request:
    branches: [ "main", "develop" ] # Cuando alguien abre un Pull Request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código (Checkout)
        uses: actions/checkout@v4

      - name: Instalar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'   
          distribution: 'temurin'
          cache: maven

      - name: Compilar y Testear con Maven
        # Si este paso falla, GitHub bloqueará el Pull Request
        run: mvn -B verify --file pom.xml
